version: '3.7'

services:
  pgsql:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
    ports:
      - 5432:5432

  php:
    build:
      context: .
    entrypoint: ./docker/php/docker-entrypoint.sh
    command: symfony server:start
    depends_on:
      - pgsql
    volumes:
      - .:/app:cached
    ports:
      - 8080:8000
